# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

min_number:
    path: /lucky/number/{min}
    controller: App\Controller\LuckyController::minNumber
    condition: "params['min'] < 100"